원본
- "교보문고_종합_베스트셀러_상품리스트-2012~2022.xlsx"

변환
- DataFrame : df_kyobo
- df_kyobo.pkl

## <작업>

In [ ]:
import pandas as pd

df_kyobo = pd.read_excel("교보문고_종합_베스트셀러_상품리스트-2012~2022.xlsx")

print(type(df_kyobo), end = '\n\n') # 데이터 타입
print(df_kyobo.shape, end = '\n\n') # 데이터 크기
print(df_kyobo.info(), end = '\n\n') # 요약정보
df_kyobo.head(3)

<class 'pandas.core.frame.DataFrame'>

(1997, 13)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1997 entries, 0 to 1996
Data columns (total 13 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   순위        1997 non-null   int64
 1   상품코드      1997 non-null   int64
 2   판매상품ID    1997 non-null   object
 3   상품명       1997 non-null   object
 4   정가        1997 non-null   object
 5   판매가       1997 non-null   object
 6   할인율       1997 non-null   object
 7   적립율       1997 non-null   object
 8   적립예정포인트   1997 non-null   object
 9   인물        1997 non-null   object
 10  출판사       1997 non-null   object
 11  발행(출시)일자  1997 non-null   int64
 12  분야        1997 non-null   object
dtypes: int64(3), object(10)
memory usage: 202.9+ KB
None

,순위,상품코드,판매상품ID,상품명,정가,판매가,할인율,적립율,적립예정포인트,인물,출판사,발행(출시)일자,분야
0,1,9788901047546,S000000401269,한 권으로 읽는 조선왕조실록,"18,000","16,200",10%,5%,900,박영규,웅진지식하우스,20130113,역사/문화
1,2,9788901047546,S000000401269,한 권으로 읽는 조선왕조실록,"18,000","16,200",10%,5%,900,박영규,웅진지식하우스,20130113,역사/문화
2,3,9788901047546,S000000401269,한 권으로 읽는 조선왕조실록,"18,000","16,200",10%,5%,900,박영규,웅진지식하우스,20130113,역사/문화

In [ ]:
# 순위열 중복 확인
print(True in (df_kyobo['순위'].value_counts() > 1), end = '\n\n') # --> False: 중복 없음


# "판매상품ID"를 기준으로 중복 된 값 제거
df_kyobo_1 = df_kyobo.drop_duplicates(subset='판매상품ID', keep='first')
print(df_kyobo_1.shape, end = '\n\n')


# "판매상품ID"를 기준으로 오름차순 정렬
df_kyobo_1  = df_kyobo_1.sort_values(by = '판매상품ID')

# []'정가', '판매가' .'적릴율', '할인율' , '적립예정포인트'] 열의 천단위 구분기호 (,), '%' 제거 후 int로 타입 변겅
df_kyobo_1['정가'] = df_kyobo_1['정가'].str.replace(',', '').astype(int)
df_kyobo_1['판매가'] = df_kyobo_1['판매가'].str.replace(',', '').astype(int)
df_kyobo_1['할인율'] = df_kyobo_1['할인율'].str.replace('%', '').astype(int)
df_kyobo_1['적립율'] = df_kyobo_1['적립율'].str.replace('%', '').astype(int)
df_kyobo_1['적립예정포인트'] = df_kyobo_1['적립예정포인트'].str.replace(',', '').astype(int)

# '발행(출시)일자' 열 (format : 2023Y12m9d)
df_kyobo_1['발행(출시)일자'] = pd.to_datetime(df_kyobo_1['발행(출시)일자'], format = '%Y%m%d')

# '인물' 열 이름을 '저자'오 변경
df_kyobo_1 = df_kyobo_1.rename(columns = {'인물' : '저자'})

# 열 순서 변경
# 변경 열 순서 : ['순위', '판매상품ID', '상품코드', '상품명', '저자', 출판사', '분야','발행(출시)일자', '정가', '판매가', '할인율', '적립율', '적립예정포인트']
df_kyobo_1 = df_kyobo_1[['순위', '판매상품ID', '상품코드', '상품명', '저자', '출판사', '분야','발행(출시)일자', '정가', '판매가', '할인율', '적립율', '적립예정포인트']]

# 덮어 쓰기 및 인덱스 초기화
df_kyobo_1 =  df_kyobo_1.reset_index(drop = True) # drop=True # 인덱스 새로 추가
df_kyobo = df_kyobo_1

# 도서 분약 분류 확인
print(df_kyobo['분야'].value_counts(), '\n\n')

print(df_kyobo.info(), end = '\n\n')
df_kyobo.head(3)

False

(1467, 13)

분야
소설          281
시/에세이       247
경제/경영       220
자기계발        199
인문          141
어린이(초등)      94
외국어          53
만화           33
정치/사회        32
역사/문화        31
가정/육아        24
예술/대중문화      19
유아(0~7세)     18
요리           13
청소년          13
건강           12
여행           11
과학           11
종교           10
컴퓨터/IT        5
Name: count, dtype: int64


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1467 entries, 0 to 1466
Data columns (total 13 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   순위        1467 non-null   int64
 1   판매상품ID    1467 non-null   object
 2   상품코드      1467 non-null   int64
 3   상품명       1467 non-null   object
 4   저자        1467 non-null   object
 5   출판사       1467 non-null   object
 6   분야        1467 non-null   object
 7   발행(출시)일자  1467 non-null   datetime64[ns]
 8   정가        1467 non-null   int32
 9   판매가       1467 non-null   int32
 10  할인율       1467 non-null   int32
 11  적립율       1467 non-null   int32
 12  적립예정포인트   1467 non-null   int32
dtypes: datetime64[ns](1), int32(5), int64(2), object(5)
memory usage: 120.5+ KB
None

,순위,판매상품ID,상품코드,상품명,저자,출판사,분야,발행(출시)일자,정가,판매가,할인율,적립율,적립예정포인트
0,1,S000000401269,9788901047546,한 권으로 읽는 조선왕조실록,박영규,웅진지식하우스,역사/문화,2013-01-13,18000,16200,10,5,900
1,4,S000000401458,9788901052922,괜찮아,최숙희,웅진주니어,유아(0~7세),2009-04-22,10000,9000,10,5,500
2,5,S000000401766,9788901058405,철학 콘서트,황광우,웅진지식하우스,인문,2006-06-28,15000,13500,10,5,750

In [ ]:
# .pkl로 저장
import pickle

df_kyobo.to_pickle('df_kyob.pkl')

## <결과물>

In [ ]:
# pkl 파일 불러오기
with open('df_kyob.pkl', 'rb') as file:
    df_kyobo = pickle.load(file)

print(type(df_kyobo), end = '\n\n' + '=' * 50 + '\n\n')
print('(Column, Row) :', df_kyobo.shape, end = '\n\n' + '=' * 50 + '\n\n')
print(df_kyobo.info(), end = '\n\n' + '=' * 50 + '\n\n')
df_kyobo.head()

<class 'pandas.core.frame.DataFrame'>

==================================================

(Column, Row) : (1467, 13)

==================================================

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1467 entries, 0 to 1466
Data columns (total 13 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   순위        1467 non-null   int64
 1   판매상품ID    1467 non-null   object
 2   상품코드      1467 non-null   int64
 3   상품명       1467 non-null   object
 4   저자        1467 non-null   object
 5   출판사       1467 non-null   object
 6   분야        1467 non-null   object
 7   발행(출시)일자  1467 non-null   datetime64[ns]
 8   정가        1467 non-null   int32
 9   판매가       1467 non-null   int32
 10  할인율       1467 non-null   int32
 11  적립율       1467 non-null   int32
 12  적립예정포인트   1467 non-null   int32
dtypes: datetime64[ns](1), int32(5), int64(2), object(5)
memory usage: 120.5+ KB
None

==================================================

,순위,판매상품ID,상품코드,상품명,저자,출판사,분야,발행(출시)일자,정가,판매가,할인율,적립율,적립예정포인트
0,1,S000000401269,9788901047546,한 권으로 읽는 조선왕조실록,박영규,웅진지식하우스,역사/문화,2013-01-13,18000,16200,10,5,900
1,4,S000000401458,9788901052922,괜찮아,최숙희,웅진주니어,유아(0~7세),2009-04-22,10000,9000,10,5,500
2,5,S000000401766,9788901058405,철학 콘서트,황광우,웅진지식하우스,인문,2006-06-28,15000,13500,10,5,750
3,6,S000000403626,9788901090184,클루지,개리 마커스,갤리온,인문,2008-11-24,13800,12420,10,5,690
4,8,S000000403841,9788901093154,넛지 : 똑똑한 선택을 이끄는 힘,리처드 탈러 외,리더스북,경제/경영,2009-04-22,15500,13950,10,5,770